name: moniepoint
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  

  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.7.0
  animate_do: ^3.3.4
  flutter_animate: ^4.5.1
  cached_network_image: ^3.4.1
  iconsax_plus: ^1.0.0
  sliding_up_panel: ^2.0.0+1
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: Euclid
      fonts:
        - asset: assets/fonts/Euclid Circular A Bold Italic.ttf
        - asset: assets/fonts/Euclid Circular A Bold.ttf
        - asset: assets/fonts/Euclid Circular A Italic.ttf
        - asset: assets/fonts/Euclid Circular A Light Italic.ttf
        - asset: assets/fonts/Euclid Circular A Light.ttf
        - asset: assets/fonts/Euclid Circular A Medium Italic.ttf
        - asset: assets/fonts/Euclid Circular A Medium.ttf
        - asset: assets/fonts/Euclid Circular A Regular.ttf
        - asset: assets/fonts/Euclid Circular A SemiBold Italic.ttf
        - asset: assets/fonts/Euclid Circular A SemiBold.ttf


